#!/bin/sh

if [[ "${1}" == "x86_64" ]]; then
	name="amd64"
elif [[ "${1}" == "i386" ]] || [[ "${1}" == "i686" ]]; then
	name="i386"
	if [[ "${3}" == "--pae" ]]; then
		name="${name}-pae"
	fi
fi
name="config.${name}"
echo "Downloading ${name} from Liquorix" > /dev/stderr
wget --quiet "http://liquorix.net/sources/${2}/${name}"
cat ${name}
